use std::{env, fs, path::Path};

fn main() {
    let out_dir = env::current_dir().unwrap();
    dbg!(&out_dir);
    let cpp_file = Path::new(&out_dir).join("main.cpp");
    let cpp_data = fs::read(cpp_file).unwrap();
    let cpp_str = String::from_utf8(cpp_data).unwrap();
    let main_path = Path::new(&out_dir).join("src/main.rs");
    let full_code = format!(r#"
#![allow(unused_must_use, non_camel_case_types)]
/// auto-generated by `build.rs`
use ferris_torture::*;
i! {{
{}
}}
"#, cpp_str);
    fs::write(&main_path, full_code).unwrap();
}